cask "legenda" do # THE FILE IS GENERATED BY script/build-brew-cask.sh
  version "0.1.1"
  sha256 "ae4a01584b82d9fc72b9867053d81a31d34702f98a3cc6e53132a0562a4d2f53"

  url "https://github.com/adlawson/legenda/releases/download/v#{version}/Legenda-v#{version}.zip"
  name "Legenda"
  desc "Menubar meeting timer that keeps a meeting to its agenda"
  homepage "https://github.com/adlawson/legenda"

  depends_on macos: ">= :sonoma" # macOS 14

  app "Legenda-v#{version}/Legenda.app"

  # Ad-hoc signed rather than notarised, so macOS would otherwise refuse the
  # first launch. must_succeed is false because the attribute is absent when the
  # zip did not come from a browser download.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Legenda.app"],
                   must_succeed: false
  end

  zap trash: [
    "~/Library/Preferences/com.andrewlawson.legenda.plist",
  ]
end
