cask "legenda" do # THE FILE IS GENERATED BY script/build-brew-cask.sh
  version "20260730"
  sha256 "b140b8623d9f1a104081f90d2cbf352f8a52f5ecd04455c33b90499c157b0cd2"

  url "https://github.com/adlawson/legenda/releases/download/v#{version}/Legenda-v#{version}.zip"
  name "Legenda"
  desc "Menubar meeting timer that keeps a meeting to its agenda"
  homepage "https://github.com/adlawson/legenda"

  # Versions are dates, which the default git strategy does not match: its regex
  # only recognises dotted versions, so it would report an older semver tag as the
  # newest release and fail `brew audit --online`.
  livecheck do
    url "https://github.com/adlawson/legenda.git"
    strategy :git
    regex(/^v?(\d{8}(?:-[0-9a-z.]+)?)$/i)
  end

  # A bare symbol already means ">=" — the string form is deprecated.
  depends_on macos: :sonoma # macOS 14

  app "Legenda-v#{version}/Legenda.app"

  # Ad-hoc signed rather than notarised, so macOS would otherwise refuse the
  # first launch. must_succeed is false because the attribute is absent when the
  # zip did not come from a browser download.
  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", "#{appdir}/Legenda.app"],
                   must_succeed: false
  end

  zap trash: "~/Library/Preferences/com.adlawson.legenda.plist"
end
