cask "legenda@20260730" do # THE FILE IS GENERATED BY script/build-brew-cask.sh
  version "20260730"
  sha256 "b140b8623d9f1a104081f90d2cbf352f8a52f5ecd04455c33b90499c157b0cd2"

  url "https://github.com/adlawson/legenda/releases/download/v#{version}/Legenda-v#{version}.zip"
  name "Legenda"
  desc "Menubar meeting timer that keeps a meeting to its agenda"
  homepage "https://github.com/adlawson/legenda"

  # Pinned to one release, so there is nothing to look for. Without this skip the
  # livecheck would resolve the newest tag, disagree with the version above, and
  # fail `brew audit --online`.
  livecheck do
    skip "Pinned release; the legenda cask tracks the newest version"
  end

  # Both casks install the same app, so only one can be present at a time.
  conflicts_with cask: "legenda"
  # A bare symbol already means ">=" — the string form is deprecated.
  depends_on macos: :sonoma # macOS 14

  app "Legenda-v#{version}/Legenda.app"

  # Ad-hoc signed rather than notarised, so macOS would otherwise refuse the
  # first launch. must_succeed is false because the attribute is absent when the
  # zip did not come from a browser download.
  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", "#{appdir}/Legenda.app"],
                   must_succeed: false
  end

  zap trash: "~/Library/Preferences/com.adlawson.legenda.plist"
end
